version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "83:83"
    volumes:
      - ./morero:/var/www/html
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw # Replace with your desired MySQL root user password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
